DROP TABLE IF EXISTS user_card;

DROP TABLE IF EXISTS users;

# DROP table IF EXISTS roles;

DROP TABLE IF EXISTS cards;

DROP TABLE IF EXISTS players;

DROP TABLE IF EXISTS teams;

DROP TABLE IF EXISTS countries;